AllCops:
  DisplayCopNames: true
  Include:
    - 'test/**/*'
    - spec
    - Rakefile
    - Guardfile
  Exclude:
    - Berksfile
    - Vagrantfile
    - Thorfile
    - Gemfile
    - bin/*
    - vendor/**/*

Layout/ExtraSpacing:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 14
Style/StringLiterals:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
